name: read-hn
version: '0.1.0.0'
category: Web
author: uuhan
maintainer: xuminhui189@gmail.com
license: BSD3

dependencies:
  - aeson
  - base
  - bytestring
  - filepath
  - unix
  - directory
  - interpolatedstring-perl6
  - lens
  - lens-aeson
  - wreq

executables:
  read-hn:
    main: Main.hs
